### PR TITLE
Enable class inheritance

### PR DESCRIPTION
**Pull request by Day0Dreamer**
With this change we can now do simple class inheritance. Similar changes are also necessary for Actor class and maybe others

### CODE REVIEW

**Comment by perrygoy** [comment]
Hi, @Day0Dreamer ! Thanks for the contribution!

I'm curious to know the use case for this change. Could you give me some context to what the benefit of subclassing `Target` and `Actor` would be?

**Comment by Day0Dreamer** [comment]
Oh... Sorry for the late reply.

Well. I wanted to give the Actor more flexibility in the way how his path
might branch out. For example after the game title screen, we should see
the loading screen, unless there is a new version and we have to account
for both possibilities. So I did:

def should_see_either_or(self, *tests: Tuple[Question, Resolution]) -> None:
    """
    Ask a series of questions, asserting their expected answers.

    Args:
        tests: tuples of a |Question| and a |Resolution|.

    Raises:
        AssertionError: If the question's actual answer does not match
            the expected answer from the |Resolution|.
    """
    tests_count = len(tests)
    success_count = 0
    failure_count = 0
    for question, test in tests:
        try:
            assert_that(question.answered_by(self), test)
            success_count += 1
            logger.trace(f"Test succeeded, and it's succession
#{success_count} out of {tests_count}")
        except AssertionError as e:
            failure_count += 1
            logger.warning(f"{e}, and it's failure #{failure_count}
out of {tests_count}")
    if success_count < 1:
        logger.error(f"Every test out of {tests} has failed")
        raise AssertionError("Every test has failed")

should_see_that_either_or = should_see_either_or

As for the Target, I'm working with the AltUnity toolset to write tests for
Unity game engine and they to really like to Tap on the screen there. Click
is something different. So this was added:

def tapped_by(self, the_actor: Actor) -> AltElement:
    """ """
    return the_actor.uses_ability_to(PlayTheGame).to_tap(self)

And to keep everything close to examples, I override the class, and import
the modified class as if it's the original one

from screenpy import Target as VanillaTarget
class Target(VanillaTarget):

So it's backwards compatible with future updates of screenpy.

I hope this email keeps its formatting and colors and you'll be able to
follow my logic here just fine :)
(That is the email reply. Let's see how github will see it)

**Comment by Day0Dreamer** [comment]
Oh... Sorry for the late reply.

Well. I wanted to give the Actor more flexibility in the way how his path might branch out. For example after the game title screen, we should see the loading screen, unless there is a new version and we have to account for both possibilities. So I did:

```
def should_see_either_or(self, *tests: Tuple[Question, Resolution]) -> None:
    tests_count = len(tests)
    success_count = 0
    failure_count = 0
    for question, test in tests:
        try:
            assert_that(question.answered_by(self), test)
            success_count += 1
            logger.trace(f"Test succeeded, and it's succession #{success_count} out of {tests_count}")
        except AssertionError as e:
            failure_count += 1
            logger.warning(f"{e}, and it's failure #{failure_count} out of {tests_count}")
    if success_count < 1:
        logger.error(f"Every test out of {tests} has failed")
        raise AssertionError("Every test has failed")

should_see_that_either_or = should_see_either_or
```

As for the Target, I'm working with the AltUnity toolset to write tests for Unity game engine and they to really like to Tap on the screen there. Click is something different. So this was added:
```
def tapped_by(self, the_actor: Actor) -> AltElement:
    """ """
    return the_actor.uses_ability_to(PlayTheGame).to_tap(self)
```
And to keep everything close to examples, I override the class, and import the modified class as if it's the original one
```
from screenpy import Target as VanillaTarget
class Target(VanillaTarget):
```
So it's backwards compatible with future updates of screenpy.

I hope this email keeps its formatting and colors and you'll be able to follow my logic here just fine :)

**Comment by perrygoy** [comment]
Hey, thanks for getting back to me! No worries about the delay.

The reason i asked for justification at all is that ScreenPy (and Screenplay Pattern itself) is written with a strong emphasis on composition instead of inheritance. So, to be honest, while it wasn't an entirely intentional action on my part to always return an `Actor` instead of `cls`, i'm not sure that it really *should*, you know what i mean?

Although on the other hand, i do want to encourage folks to use this library in the way that makes the most sense to them. I'll think about it for a little bit.

For your `Target` example, though—unless i'm misunderstanding something—i think you might want to [write a custom Action](https://screenpy-docs.readthedocs.io/en/latest/module/actions.html#writing-new-actions) instead of extending what a `Target` does. You could write a `Tap` action that takes a `Target` and taps it, doing essentially exactly what you have in the example. Does that fit the functionality you were hoping for?

**Comment by Day0Dreamer** [comment]
Interesting. I did write a custon Tap, but you make it sounds like I did it the wrong way around. I use the Target inside that Tap :D

`
class Tap(BaseAction):
    target: Target
`
` @staticmethod
    def on_the(target: Target) -> "Tap":
        return Tap(target)

    on = on_the

    @beat("{0} Taps '{target}'...")
    def perform_as(self, the_actor: Actor) -> None:
        """
        Direct the actor to click on the element described by the given target.

        Args:
            the_actor: the |Actor| who will perform the action.

        Raises:
            |DeliveryError|: an exception was raised by Selenium.
            |UnableToPerform|: the actor does not have the ability to
                |BrowseTheWeb|.
        """
        logger.trace(f"{the_actor} Taps '{self.target}'...")
        element = self.target.found_by(the_actor)

        try:
            element.tap()
        except AltUnityException as e:  # TODO THIS IS ERROR
            msg = (
                "Encountered an issue while attempting to click "
                f"{self.target}: {e.__class__.__name__}"
            )
            raise AltUnityException(msg).with_traceback(e.__traceback__)

    def add_to_chain(self, the_actor: Actor, the_chain: ActionChains) -> None:
        """
        Add the Click action to an in-progress |Chain| of actions.

        Args:
            the_actor: the |Actor| who will be performing the action chain.
            the_chain: the |ActionChains| instance that is being built.
        """
        the_chain.click(self.target.found_by(the_actor))

    def __init__(self, target: Target) -> None:
        self.target = target
`

Sorry. Don't know why the CODE is breaking apart at the @ char. Weird

**Comment by perrygoy** [comment]
Haha, that's exactly what i meant. :)

If you don't mind, i think i'll close these two PRs. The `Target` modification seems like it should be a custom `Tap` action (that you've already got, nice!), and the `Actor` modification sounds like something that i actually want to be in ScreenPy itself!

Do you want to open a new PR for the `should_see_at_least_one_of` method? I'd love to incorporate that and want you to have your name on it (but please don't include the `# DAY0` comment, `git blame` will tell everyone who did it 🙂 ).

**Comment by Day0Dreamer** [comment]
Yeah, I'm still getting around those requests :) Will do closer to the weekend :) Thanks!

**Comment by perrygoy** [comment]
I look forward to your new PR!

**Comment by perrygoy** [comment]
@Day0Dreamer i haven't heard from you in a while, but i added the functionality we talked about in the 2.1.1 update. Take a look at the documentation and let me know if it suits your purposes!

[Actor's `should_see_any_of` method](https://screenpy-docs.readthedocs.io/en/latest/topics/actors.html#screenpy.actor.Actor.should_see_any_of)

**Pull request closed without merging**
