### PR TITLE
adding convenience methods for abilities

### PR DESCRIPTION
**Pull request by bandophahita**
For those times when we need the object the actor's ability provides. 
```python
driver = BrowseTheWeb.as_(actor)
```
vs 
```python
driver = actor.uses_ability_to(BrowseTheWeb)
```

### CODE REVIEW

**Comment by perrygoy** [comment]
I think i'm going to deny this one. 

As the library is right now, Abilities know nothing about Actors. You could use all the methods of the abilities directly without any actors. I think having abilities understand how to extract themselves from actors feels like an intrusion on actors and a violation of abilities' directive, or something. 

I've been hesitating to say it violates the Single Responsibility Principle, but i guess that's what i'm saying it does. :P

**Comment by bandophahita** [comment]
I kept thinking this might violate the dependency inversion principle but only because of the type hint.  Which could easily be handled by using the `if TYPE_CHECKING:` import trick. 

I hear your concern and I had the same initially.  Abilities should be independent of actors.  And yet Actors are the only entities that have abilities (so far).  _Here is where I feel I need someone to perhaps correct my thinking about the idea._

If that were to change in the future would a protocol need to be created for actors and (yet to be considered entity)?  In which case the new entity would also need a method to utilize an ability.  Therefore I reasoned that if such a protocol were to exist for actors, the method `uses_ability_to` would be part of that protocol.    

Somehow when I considered the possibility of a protocol existing it felt ok to allow for this type of convenience method.  I also felt like the readability factor somehow  made it ok as if to say, if it reads well in screenplay pattern it must be right with SOLID.  Have I fooled myself?

**Comment by perrygoy** [comment]
I think i've figured out why i feel like it's weird. It feels like we're going up a level in our abstraction barriers. It's not an exact analogy because Abilities are more of a container than a barrier, but it feels like we're going against the grain.

Maybe i'd understand this a bit better if you gave some context for why you want this function. What are you trying to do that will be made easier than `the_actor.ability_to(BrowseTheWeb)`? 

> Actors are the only entities that have abilities (so far).

I'll admit, i have no idea what other thing might use abilities. The closest i've come is an actor that handles set-up and having fun thoughts about making a new Actor type that is explicitly for that sort of job, like a Stage Tech or something. :P

**Comment by bandophahita** [comment]
> What are you trying to do that will be made easier than `the_actor.ability_to(BrowseTheWeb)`?

My motivation is mostly readability.  `BrowseTheWeb.as_(actor)` felt shorter and easier to read.
I came across the idea here - https://janmolak.com/serenity-bdd-and-the-screenplay-pattern-27819d0db780 after I had already implemented almost exactly the same `Authenticate` ability.

**Comment by perrygoy** [comment]
It is shorter, and it is easy to read. But i don't think i like the way it points the arrow back up. There's just something that feels a little off to me about asking the ability to get itself. 

SerenityBDD, which is the more popular Java/C#/Javascript library, does use this `as` method. It looks like they've got a `RefersToActor` interface in the Java version, from their docs. 

I think there should be just one way to do this. I'll keep this PR open and keep thinking about it for a bit; i need to put my finger on why this doesn't feel right to me.

**Comment by bandophahita** [comment]
I brought this one up with my team and they had similar conclusions as you did; adding this would violate dependency inversion principle.   I have to say I agree.

One idea was "if you _really_ want that convenience of a shorter call, just add a utility function that isn't part of the ability"
```python
def browse_the_web_as(actor: Actor):
    return actor.uses_ability_to(BrowseTheWeb)
```
But at that point the only purpose it serves it to save keystrokes.  So unless you can think of an acceptable alternative, I'll close the PR.

**Pull request closed without merging**
