### PR TITLE
Add IsCloseTo resolution

### PR DESCRIPTION
**Pull request by langgaibo**
Adds a new resolution `IsCloseTo` which allows a value comparison to match an asserted value with a delta value.

### CODE REVIEW

**Review by perrygoy — APPROVED** [review]
Thanks for the addition, @langgaibo! 👍

**Comment by bandophahita** [comment]
"close" is a relative term.  Given that relativity I would think this resolution would make a good recipe but not be included in the base library.

**Comment by perrygoy** [comment]
> "close" is a relative term. 

True, but given that you supply the delta which defines the relativity, i think it becomes somewhat concrete. 

I hear what you're saying though, it might be hard to think of how this might be useful to anyone just wanting to use ScreenPy. I've personally been of the opinion that if someone finds a resolution useful, then others probably will, too. As long as it's generalizable, i'm OK with it being in the main library.

**Comment by bandophahita** [comment]
>  you supply the delta
🤦‍♂️ Time for more coffee. 
I glanced at the changes and missed that.  I agree, with the ability to provide the relative context for 'close' this works just fine.

**Pull request merged**
